import { defineConfig, type DefaultTheme, type HeadConfig } from 'vitepress'

const siteUrl = 'https://pstarh.github.io/commander-docs/'
const description =
  'Multi-agent orchestration engine — 25 providers · 5 canonical topologies · 18 built-in tools · 6700+ tests'

const descriptions: Record<string, string> = {
  en: description,
  zh: '多代理编排引擎 — 25 家模型提供商 · 5 种规范拓扑 · 18 内置工具 · 6700+ 测试',
  ja: 'マルチエージェント編成エンジン — 25 プロバイダー · 5 トポロジ · 18 ツール · 6700+ テスト',
  ko: '멀티 에이전트 오케스트레이션 엔진 — 25 프로바이더 · 5 토폴로지 · 18 도구 · 6700+ 테스트',
  es: 'Motor de orquestación multi-agente — 25 proveedores · 5 topologías · 18 herramientas · 6700+ tests',
  fr: 'Moteur d’orchestration multi-agents — 25 fournisseurs · 5 topologies · 18 outils · 6700+ tests',
}

const head: HeadConfig[] = [
  ['link', { rel: 'icon', href: '/commander-docs/favicon.svg', type: 'image/svg+xml' }],
  ['meta', { name: 'theme-color', content: '#09090b' }],
  ['meta', { name: 'author', content: 'Commander Contributors' }],
  [
    'meta',
    {
      name: 'keywords',
      content:
        'multi-agent, orchestration, LLM, commander, AI agents, SSE, topology, 多代理, マルチエージェント, 멀티에이전트',
    },
  ],
  ['meta', { property: 'og:type', content: 'website' }],
  ['meta', { property: 'og:url', content: siteUrl }],
  ['meta', { property: 'og:title', content: 'Commander — Multi-Agent Orchestration Engine' }],
  ['meta', { property: 'og:description', content: description }],
  ['meta', { property: 'og:site_name', content: 'Commander Docs' }],
  ['meta', { property: 'og:image', content: 'https://pstarh.github.io/commander-docs/og.png' }],
  ['meta', { property: 'og:image:width', content: '1200' }],
  ['meta', { property: 'og:image:height', content: '630' }],
  ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
  ['meta', { name: 'twitter:title', content: 'Commander — Multi-Agent Orchestration Engine' }],
  ['meta', { name: 'twitter:description', content: description }],
  ['meta', { name: 'twitter:image', content: 'https://pstarh.github.io/commander-docs/og.png' }],
  [
    'script',
    { type: 'application/ld+json' },
    JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Commander',
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'Cross-platform',
      license: 'https://opensource.org/licenses/MIT',
      url: 'https://github.com/PStarH/Commander',
      description,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    }),
  ],
]

type L = 'en' | 'zh' | 'ja' | 'ko' | 'es' | 'fr'

function p(locale: L, path: string): string {
  if (locale === 'en') return path
  return `/${locale}${path}`
}

function guideSidebar(locale: L, t: Record<string, string>): DefaultTheme.SidebarItem[] {
  const L = (path: string) => p(locale, path)
  return [
    {
      text: t.gettingStarted,
      items: [
        { text: t.quickStart, link: L('/guide/getting-started') },
        { text: t.why, link: L('/guide/why-commander') },
        { text: t.install, link: L('/guide/installation') },
        { text: t.console, link: L('/guide/web-console') },
        { text: t.topologyExplorer, link: L('/guide/topology-explorer') },
        { text: t.commands, link: L('/guide/commands') },
        { text: t.providers, link: L('/guide/providers') },
        { text: t.config, link: L('/guide/configuration') },
      ],
    },
    {
      text: t.cookbook,
      items: [
        { text: t.overview, link: L('/guide/cookbook/') },
        { text: t.cbSecurity, link: L('/guide/cookbook/security-audit') },
        { text: t.cbRefactor, link: L('/guide/cookbook/refactor-module') },
        { text: t.cbCi, link: L('/guide/cookbook/ci-full-auto') },
      ],
    },
    {
      text: t.usage,
      items: [
        { text: t.running, link: L('/guide/usage/running-tasks') },
        { text: t.plan, link: L('/guide/usage/plan-mode') },
        { text: t.watch, link: L('/guide/usage/watch-mode') },
        { text: t.topologyTree, link: L('/guide/usage/topology-decision-tree') },
        { text: t.chaos, link: L('/guide/usage/chaos-testing') },
        { text: t.shadow, link: L('/guide/usage/shadow-traffic') },
      ],
    },
    {
      text: t.advanced,
      items: [
        { text: t.teams, link: L('/guide/advanced/agent-teams') },
        { text: t.customProviders, link: L('/guide/advanced/custom-providers') },
        { text: t.customTools, link: L('/guide/advanced/custom-tools') },
        { text: t.plugins, link: L('/guide/advanced/plugin-system') },
        { text: t.rag, link: L('/guide/advanced/rag-knowledge-base') },
        { text: t.security, link: L('/guide/security') },
        { text: t.migration, link: L('/guide/migration-v2') },
      ],
    },
    {
      text: t.sdkRef,
      items: [
        { text: t.sdk, link: L('/guide/sdk') },
        { text: t.sdkPy, link: L('/guide/sdk-python') },
        { text: t.benchmarks, link: L('/guide/benchmarks') },
        { text: t.troubleshoot, link: L('/guide/troubleshooting') },
        { text: t.faq, link: L('/guide/faq') },
        { text: t.contributing, link: L('/guide/contributing') },
        { text: t.showcase, link: L('/guide/showcase') },
        { text: t.changelog, link: L('/guide/changelog') },
      ],
    },
  ]
}

function architectureSidebar(locale: L, t: Record<string, string>): DefaultTheme.SidebarItem[] {
  const L = (path: string) => p(locale, path)
  return [
    {
      text: t.startHere,
      items: [
        { text: t.overview, link: L('/architecture/overview') },
        { text: t.coreChain, link: L('/architecture/core-call-chain') },
        { text: t.multiAgent, link: L('/architecture/multi-agent') },
        { text: t.agentRuntime, link: L('/architecture/agent-runtime') },
      ],
    },
    {
      text: t.core,
      collapsed: true,
      items: [
        { text: t.router, link: L('/architecture/smart-model-router') },
        { text: t.advFeat, link: L('/architecture/advanced-features') },
      ],
    },
    {
      text: t.reliability,
      collapsed: true,
      items: [
        { text: t.resilience, link: L('/architecture/resilience') },
        { text: t.eventSrc, link: L('/architecture/event-sourcing') },
        { text: t.saga, link: L('/architecture/saga') },
        { text: t.atr, link: L('/architecture/atr') },
        { text: t.supervision, link: L('/architecture/supervision-tree') },
        { text: t.backpressure, link: L('/architecture/backpressure') },
        { text: t.verification, link: L('/architecture/verification') },
        { text: t.caching, link: L('/architecture/caching') },
      ],
    },
    {
      text: t.performance,
      collapsed: true,
      items: [
        { text: t.speculative, link: L('/architecture/speculative-execution') },
        { text: t.intelligence, link: L('/architecture/intelligence') },
      ],
    },
    {
      text: t.security,
      collapsed: true,
      items: [
        { text: t.secGateway, link: L('/architecture/security-gateway') },
        { text: t.sandbox, link: L('/architecture/sandbox') },
        { text: t.multiTenant, link: L('/architecture/multi-tenancy') },
      ],
    },
    {
      text: t.systems,
      collapsed: true,
      items: [
        { text: t.tools, link: L('/architecture/tools') },
        { text: t.mcp, link: L('/architecture/mcp') },
        { text: t.channels, link: L('/architecture/channel-adapters') },
        { text: t.skills, link: L('/architecture/skills-system') },
        { text: t.selfEvo, link: L('/architecture/self-evolution') },
        { text: t.prodReady, link: L('/architecture/production-readiness') },
        { text: t.extensions, link: L('/architecture/extension-points') },
      ],
    },
  ]
}

function apiSidebar(locale: L, t: Record<string, string>): DefaultTheme.SidebarItem[] {
  const L = (path: string) => p(locale, path)
  return [
    {
      text: t.publicApi,
      items: [{ text: t.apiOverview, link: L('/api/overview') }],
    },
    {
      text: t.runtimeApi,
      items: [
        { text: t.taskComplexity, link: L('/api/task-complexity-analyzer') },
        { text: t.adaptive, link: L('/api/adaptive-orchestrator') },
        { text: t.tokenBudget, link: L('/api/token-budget-allocator') },
        { text: t.memory, link: L('/api/three-layer-memory') },
        { text: t.reflection, link: L('/api/reflection-engine') },
        { text: t.consensus, link: L('/api/consensus-checker') },
        { text: t.inspector, link: L('/api/inspector-agent') },
      ],
    },
  ]
}

const UI = {
  en: {
    gettingStarted: 'Getting Started',
    quickStart: 'Quick Start',
    why: 'Why Commander',
    install: 'Installation',
    console: 'Web Console',
    topologyExplorer: 'Topology Explorer',
    commands: 'Commands',
    providers: 'Providers',
    config: 'Configuration',
    cookbook: 'Cookbook',
    overview: 'Overview',
    cbSecurity: 'Security audit',
    cbRefactor: 'Refactor a module',
    cbCi: 'CI full-auto lint fix',
    usage: 'Usage',
    running: 'Running Tasks',
    plan: 'Plan Mode',
    watch: 'Watch Mode',
    topologyTree: 'Topology Decision Tree',
    chaos: 'Chaos Testing',
    shadow: 'Shadow Traffic',
    advanced: 'Advanced',
    teams: 'Agent Teams',
    customProviders: 'Custom Providers',
    customTools: 'Custom Tools',
    plugins: 'Plugin System',
    rag: 'RAG Knowledge Base',
    security: 'Security',
    migration: 'V2 Migration',
    sdkRef: 'SDK & Reference',
    sdk: 'Agent SDK',
    sdkPy: 'Python SDK',
    benchmarks: 'Benchmarks',
    troubleshoot: 'Troubleshooting',
    faq: 'FAQ',
    contributing: 'Contributing',
    showcase: 'Showcase',
    changelog: 'Changelog',
    startHere: 'Start here',
    core: 'Core',
    coreChain: 'Core Call Chain',
    multiAgent: 'Multi-Agent Orchestration',
    agentRuntime: 'Agent Runtime',
    router: 'Smart Model Router',
    advFeat: 'Advanced Features',
    reliability: 'Reliability',
    resilience: 'Resilience',
    eventSrc: 'Event Sourcing & Recovery',
    saga: 'Saga Transactions',
    atr: 'Agent Transaction Runtime',
    supervision: 'Supervision Tree',
    backpressure: 'Backpressure Control',
    verification: 'Verification Pipeline',
    caching: 'Caching',
    performance: 'Performance',
    speculative: 'Speculative Execution',
    intelligence: 'Intelligence Layer',
    secGateway: 'Security Gateway',
    sandbox: 'Security Sandbox',
    multiTenant: 'Multi-Tenancy',
    systems: 'Systems',
    tools: 'Tools',
    mcp: 'MCP Integration',
    channels: 'Channel Adapters',
    skills: 'Skills System',
    selfEvo: 'Self-Evolution',
    prodReady: 'Production Readiness',
    extensions: 'Extension Points',
    publicApi: 'Public integration',
    apiOverview: 'Overview (Layer 1 & 2)',
    runtimeApi: 'Runtime components (Layer 2)',
    taskComplexity: 'Task Complexity Analyzer',
    adaptive: 'Adaptive Orchestrator',
    tokenBudget: 'Token Budget Allocator',
    memory: 'Three-Layer Memory',
    reflection: 'Reflection Engine',
    consensus: 'Consensus Checker',
    inspector: 'Inspector Agent',
    navGuide: 'Guide',
    navArch: 'Architecture',
    navApi: 'API',
    navCook: 'Cookbook',
    navDeploy: 'Deployment',
    navCommunity: 'Community',
    edit: 'Edit this page on GitHub',
    updated: 'Updated at',
    onThisPage: 'On this page',
    prev: 'Previous',
    next: 'Next',
    footerMsg: 'MIT Licensed — Built for multi-agent orchestration.',
  },
  zh: {
    gettingStarted: '入门',
    quickStart: '快速开始',
    why: '为什么选 Commander',
    install: '安装',
    console: 'Web 控制台',
    topologyExplorer: '拓扑探索器',
    commands: '命令',
    providers: '提供商',
    config: '配置',
    cookbook: '实战手册',
    overview: '概览',
    cbSecurity: '安全审计',
    cbRefactor: '安全重构模块',
    cbCi: 'CI 全自动修 lint',
    usage: '用法',
    running: '运行任务',
    plan: '计划模式',
    watch: '监视模式',
    topologyTree: '拓扑决策树',
    chaos: '混沌测试',
    shadow: '影子流量',
    advanced: '进阶',
    teams: '代理团队',
    customProviders: '自定义提供商',
    customTools: '自定义工具',
    plugins: '插件系统',
    rag: 'RAG 知识库',
    security: '安全',
    migration: 'V2 迁移',
    sdkRef: 'SDK 与参考',
    sdk: 'Agent SDK',
    sdkPy: 'Python SDK',
    benchmarks: '基准测试',
    troubleshoot: '故障排除',
    faq: '常见问题',
    contributing: '贡献指南',
    showcase: '案例展示',
    changelog: '更新日志',
    startHere: '从这里开始',
    core: '核心',
    coreChain: '核心调用链',
    multiAgent: '多代理编排',
    agentRuntime: '代理运行时',
    router: '智能模型路由',
    advFeat: '高级特性',
    reliability: '可靠性',
    resilience: '弹性',
    eventSrc: '事件溯源与恢复',
    saga: 'Saga 事务',
    atr: '代理事务运行时',
    supervision: '监督树',
    backpressure: '背压控制',
    verification: '校验流水线',
    caching: '缓存',
    performance: '性能',
    speculative: '推测执行',
    intelligence: '智能层',
    secGateway: '安全网关',
    sandbox: '安全沙箱',
    multiTenant: '多租户',
    systems: '系统',
    tools: '工具',
    mcp: 'MCP 集成',
    channels: '通道适配器',
    skills: '技能系统',
    selfEvo: '自进化',
    prodReady: '生产就绪',
    extensions: '扩展点',
    publicApi: '公共集成',
    apiOverview: '概览（第 1 / 2 层）',
    runtimeApi: '运行时组件（第 2 层）',
    taskComplexity: '任务复杂度分析器',
    adaptive: '自适应编排器',
    tokenBudget: 'Token 预算分配器',
    memory: '三层记忆',
    reflection: '反思引擎',
    consensus: '共识检查器',
    inspector: '巡检代理',
    navGuide: '指南',
    navArch: '架构',
    navApi: 'API',
    navCook: '实战手册',
    navDeploy: '部署',
    navCommunity: '社区',
    edit: '在 GitHub 上编辑此页',
    updated: '更新于',
    onThisPage: '本页目录',
    prev: '上一页',
    next: '下一页',
    footerMsg: 'MIT 许可 — 为多代理编排而生。',
  },
  ja: {
    gettingStarted: 'はじめに',
    quickStart: 'クイックスタート',
    why: 'なぜ Commander か',
    install: 'インストール',
    console: 'Web コンソール',
    topologyExplorer: 'トポロジエクスプローラー',
    commands: 'コマンド',
    providers: 'プロバイダー',
    config: '設定',
    cookbook: 'クックブック',
    overview: '概要',
    cbSecurity: 'セキュリティ監査',
    cbRefactor: 'モジュールリファクタ',
    cbCi: 'CI 全自動 lint 修正',
    usage: '使い方',
    running: 'タスク実行',
    plan: 'プランモード',
    watch: 'ウォッチモード',
    topologyTree: 'トポロジ決定木',
    chaos: 'カオステスト',
    shadow: 'シャドートラフィック',
    advanced: '高度な話題',
    teams: 'エージェントチーム',
    customProviders: 'カスタムプロバイダー',
    customTools: 'カスタムツール',
    plugins: 'プラグイン',
    rag: 'RAG ナレッジベース',
    security: 'セキュリティ',
    migration: 'V2 移行',
    sdkRef: 'SDK とリファレンス',
    sdk: 'Agent SDK',
    sdkPy: 'Python SDK',
    benchmarks: 'ベンチマーク',
    troubleshoot: 'トラブルシューティング',
    faq: 'FAQ',
    contributing: 'コントリビュート',
    showcase: 'ショーケース',
    changelog: '変更履歴',
    startHere: 'ここから',
    core: 'コア',
    coreChain: 'コア呼び出しチェーン',
    multiAgent: 'マルチエージェント編成',
    agentRuntime: 'エージェントランタイム',
    router: 'スマートモデルルーター',
    advFeat: '高度な機能',
    reliability: '信頼性',
    resilience: 'レジリエンス',
    eventSrc: 'イベントソーシング',
    saga: 'Saga',
    atr: 'ATR',
    supervision: 'スーパービジョンツリー',
    backpressure: 'バックプレッシャー',
    verification: '検証パイプライン',
    caching: 'キャッシュ',
    performance: 'パフォーマンス',
    speculative: '投機的実行',
    intelligence: 'インテリジェンス層',
    secGateway: 'セキュリティゲートウェイ',
    sandbox: 'サンドボックス',
    multiTenant: 'マルチテナンシー',
    systems: 'システム',
    tools: 'ツール',
    mcp: 'MCP',
    channels: 'チャネルアダプター',
    skills: 'スキル',
    selfEvo: '自己進化',
    prodReady: '本番準備',
    extensions: '拡張ポイント',
    publicApi: '公開統合',
    apiOverview: '概要（レイヤー 1 & 2）',
    runtimeApi: 'ランタイムコンポーネント',
    taskComplexity: 'タスク複雑度',
    adaptive: '適応型オーケストレーター',
    tokenBudget: 'トークン予算',
    memory: '3 層メモリ',
    reflection: 'リフレクション',
    consensus: 'コンセンサス',
    inspector: 'インスペクター',
    navGuide: 'ガイド',
    navArch: 'アーキテクチャ',
    navApi: 'API',
    navCook: 'クックブック',
    navDeploy: 'デプロイ',
    navCommunity: 'コミュニティ',
    edit: 'GitHub で編集',
    updated: '更新日',
    onThisPage: 'このページ',
    prev: '前へ',
    next: '次へ',
    footerMsg: 'MIT — マルチエージェント編成のために。',
  },
  ko: {
    gettingStarted: '시작하기',
    quickStart: '빠른 시작',
    why: '왜 Commander인가',
    install: '설치',
    console: '웹 콘솔',
    topologyExplorer: '토폴로지 탐색기',
    commands: '명령',
    providers: '프로바이더',
    config: '구성',
    cookbook: '쿡북',
    overview: '개요',
    cbSecurity: '보안 감사',
    cbRefactor: '모듈 리팩터',
    cbCi: 'CI 자동 lint 수정',
    usage: '사용법',
    running: '작업 실행',
    plan: '플랜 모드',
    watch: '워치 모드',
    topologyTree: '토폴로지 결정 트리',
    chaos: '카오스 테스트',
    shadow: '섀도 트래픽',
    advanced: '고급',
    teams: '에이전트 팀',
    customProviders: '커스텀 프로바이더',
    customTools: '커스텀 도구',
    plugins: '플러그인',
    rag: 'RAG 지식 베이스',
    security: '보안',
    migration: 'V2 마이그레이션',
    sdkRef: 'SDK 및 참조',
    sdk: 'Agent SDK',
    sdkPy: 'Python SDK',
    benchmarks: '벤치마크',
    troubleshoot: '문제 해결',
    faq: 'FAQ',
    contributing: '기여',
    showcase: '쇼케이스',
    changelog: '변경 로그',
    startHere: '여기서 시작',
    core: '코어',
    coreChain: '핵심 호출 체인',
    multiAgent: '멀티 에이전트',
    agentRuntime: '에이전트 런타임',
    router: '스마트 모델 라우터',
    advFeat: '고급 기능',
    reliability: '신뢰성',
    resilience: '복원력',
    eventSrc: '이벤트 소싱',
    saga: 'Saga',
    atr: 'ATR',
    supervision: '슈퍼비전 트리',
    backpressure: '백프레셔',
    verification: '검증 파이프라인',
    caching: '캐싱',
    performance: '성능',
    speculative: '추측 실행',
    intelligence: '인텔리전스',
    secGateway: '보안 게이트웨이',
    sandbox: '샌드박스',
    multiTenant: '멀티 테넌시',
    systems: '시스템',
    tools: '도구',
    mcp: 'MCP',
    channels: '채널 어댑터',
    skills: '스킬',
    selfEvo: '자가 진화',
    prodReady: '프로덕션 준비',
    extensions: '확장 지점',
    publicApi: '공개 통합',
    apiOverview: '개요 (레이어 1 & 2)',
    runtimeApi: '런타임 컴포넌트',
    taskComplexity: '작업 복잡도',
    adaptive: '적응형 오케스트레이터',
    tokenBudget: '토큰 예산',
    memory: '3계층 메모리',
    reflection: '리플렉션',
    consensus: '합의',
    inspector: '인스펙터',
    navGuide: '가이드',
    navArch: '아키텍처',
    navApi: 'API',
    navCook: '쿡북',
    navDeploy: '배포',
    navCommunity: '커뮤니티',
    edit: 'GitHub에서 편집',
    updated: '업데이트',
    onThisPage: '이 페이지',
    prev: '이전',
    next: '다음',
    footerMsg: 'MIT — 멀티 에이전트 오케스트레이션을 위해.',
  },
  es: {
    gettingStarted: 'Primeros pasos',
    quickStart: 'Inicio rápido',
    why: 'Por qué Commander',
    install: 'Instalación',
    console: 'Consola web',
    topologyExplorer: 'Explorador de topología',
    commands: 'Comandos',
    providers: 'Proveedores',
    config: 'Configuración',
    cookbook: 'Cookbook',
    overview: 'Resumen',
    cbSecurity: 'Auditoría de seguridad',
    cbRefactor: 'Refactorizar un módulo',
    cbCi: 'CI full-auto lint',
    usage: 'Uso',
    running: 'Ejecutar tareas',
    plan: 'Modo plan',
    watch: 'Modo watch',
    topologyTree: 'Árbol de topología',
    chaos: 'Chaos testing',
    shadow: 'Tráfico sombra',
    advanced: 'Avanzado',
    teams: 'Equipos de agentes',
    customProviders: 'Proveedores custom',
    customTools: 'Tools custom',
    plugins: 'Plugins',
    rag: 'Base RAG',
    security: 'Seguridad',
    migration: 'Migración V2',
    sdkRef: 'SDK y referencia',
    sdk: 'Agent SDK',
    sdkPy: 'Python SDK',
    benchmarks: 'Benchmarks',
    troubleshoot: 'Solución de problemas',
    faq: 'FAQ',
    contributing: 'Contribuir',
    showcase: 'Showcase',
    changelog: 'Changelog',
    startHere: 'Empieza aquí',
    core: 'Núcleo',
    coreChain: 'Cadena de llamadas',
    multiAgent: 'Orquestación multi-agente',
    agentRuntime: 'Runtime de agentes',
    router: 'Router de modelos',
    advFeat: 'Funciones avanzadas',
    reliability: 'Fiabilidad',
    resilience: 'Resiliencia',
    eventSrc: 'Event sourcing',
    saga: 'Saga',
    atr: 'ATR',
    supervision: 'Árbol de supervisión',
    backpressure: 'Backpressure',
    verification: 'Pipeline de verificación',
    caching: 'Caché',
    performance: 'Rendimiento',
    speculative: 'Ejecución especulativa',
    intelligence: 'Capa de inteligencia',
    secGateway: 'Gateway de seguridad',
    sandbox: 'Sandbox',
    multiTenant: 'Multi-tenant',
    systems: 'Sistemas',
    tools: 'Tools',
    mcp: 'MCP',
    channels: 'Adaptadores de canal',
    skills: 'Skills',
    selfEvo: 'Auto-evolución',
    prodReady: 'Listo para producción',
    extensions: 'Puntos de extensión',
    publicApi: 'Integración pública',
    apiOverview: 'Resumen (capas 1 y 2)',
    runtimeApi: 'Componentes runtime',
    taskComplexity: 'Analizador de complejidad',
    adaptive: 'Orquestador adaptativo',
    tokenBudget: 'Presupuesto de tokens',
    memory: 'Memoria de 3 capas',
    reflection: 'Motor de reflexión',
    consensus: 'Consenso',
    inspector: 'Inspector',
    navGuide: 'Guía',
    navArch: 'Arquitectura',
    navApi: 'API',
    navCook: 'Cookbook',
    navDeploy: 'Despliegue',
    navCommunity: 'Comunidad',
    edit: 'Editar en GitHub',
    updated: 'Actualizado',
    onThisPage: 'En esta página',
    prev: 'Anterior',
    next: 'Siguiente',
    footerMsg: 'MIT — Hecho para orquestación multi-agente.',
  },
  fr: {
    gettingStarted: 'Premiers pas',
    quickStart: 'Démarrage rapide',
    why: 'Pourquoi Commander',
    install: 'Installation',
    console: 'Console web',
    topologyExplorer: 'Explorateur de topologie',
    commands: 'Commandes',
    providers: 'Fournisseurs',
    config: 'Configuration',
    cookbook: 'Cookbook',
    overview: 'Vue d’ensemble',
    cbSecurity: 'Audit de sécurité',
    cbRefactor: 'Refactoriser un module',
    cbCi: 'CI full-auto lint',
    usage: 'Utilisation',
    running: 'Exécuter des tâches',
    plan: 'Mode plan',
    watch: 'Mode watch',
    topologyTree: 'Arbre de topologie',
    chaos: 'Chaos testing',
    shadow: 'Trafic fantôme',
    advanced: 'Avancé',
    teams: 'Équipes d’agents',
    customProviders: 'Fournisseurs custom',
    customTools: 'Tools custom',
    plugins: 'Plugins',
    rag: 'Base RAG',
    security: 'Sécurité',
    migration: 'Migration V2',
    sdkRef: 'SDK et référence',
    sdk: 'Agent SDK',
    sdkPy: 'Python SDK',
    benchmarks: 'Benchmarks',
    troubleshoot: 'Dépannage',
    faq: 'FAQ',
    contributing: 'Contribuer',
    showcase: 'Showcase',
    changelog: 'Changelog',
    startHere: 'Commencer ici',
    core: 'Cœur',
    coreChain: 'Chaîne d’appels',
    multiAgent: 'Orchestration multi-agents',
    agentRuntime: 'Runtime agents',
    router: 'Routeur de modèles',
    advFeat: 'Fonctions avancées',
    reliability: 'Fiabilité',
    resilience: 'Résilience',
    eventSrc: 'Event sourcing',
    saga: 'Saga',
    atr: 'ATR',
    supervision: 'Arbre de supervision',
    backpressure: 'Backpressure',
    verification: 'Pipeline de vérification',
    caching: 'Cache',
    performance: 'Performance',
    speculative: 'Exécution spéculative',
    intelligence: 'Couche intelligence',
    secGateway: 'Gateway de sécurité',
    sandbox: 'Sandbox',
    multiTenant: 'Multi-tenant',
    systems: 'Systèmes',
    tools: 'Tools',
    mcp: 'MCP',
    channels: 'Adaptateurs de canal',
    skills: 'Skills',
    selfEvo: 'Auto-évolution',
    prodReady: 'Prêt production',
    extensions: 'Points d’extension',
    publicApi: 'Intégration publique',
    apiOverview: 'Vue d’ensemble (couches 1 et 2)',
    runtimeApi: 'Composants runtime',
    taskComplexity: 'Analyseur de complexité',
    adaptive: 'Orchestrateur adaptatif',
    tokenBudget: 'Budget de tokens',
    memory: 'Mémoire à 3 couches',
    reflection: 'Moteur de réflexion',
    consensus: 'Consensus',
    inspector: 'Inspecteur',
    navGuide: 'Guide',
    navArch: 'Architecture',
    navApi: 'API',
    navCook: 'Cookbook',
    navDeploy: 'Déploiement',
    navCommunity: 'Communauté',
    edit: 'Modifier sur GitHub',
    updated: 'Mis à jour',
    onThisPage: 'Sur cette page',
    prev: 'Précédent',
    next: 'Suivant',
    footerMsg: 'MIT — Conçu pour l’orchestration multi-agents.',
  },
} as const

function themeFor(locale: L): DefaultTheme.Config {
  const t = UI[locale]
  const prefix = locale === 'en' ? '' : `/${locale}`
  const guideKey = locale === 'en' ? '/guide/' : `/${locale}/guide/`
  const archKey = locale === 'en' ? '/architecture/' : `/${locale}/architecture/`
  const apiKey = locale === 'en' ? '/api/' : `/${locale}/api/`

  return {
    logo: '/logo.svg',
    siteTitle: 'Commander',
    nav: [
      { text: t.navGuide, link: `${prefix}/guide/getting-started`, activeMatch: `${prefix}/guide/` },
      {
        text: t.navArch,
        link: `${prefix}/architecture/overview`,
        activeMatch: `${prefix}/architecture/`,
      },
      { text: t.navApi, link: `${prefix}/api/overview`, activeMatch: `${prefix}/api/` },
      { text: t.navCook, link: `${prefix}/guide/cookbook/`, activeMatch: `${prefix}/guide/cookbook/` },
      {
        text: t.navDeploy,
        link: locale === 'en' ? '/deployment' : `${prefix}/deployment`,
        activeMatch: locale === 'en' ? '/deployment' : `${prefix}/deployment`,
      },
      {
        text: t.navCommunity,
        link: locale === 'en' ? '/community' : `${prefix}/community`,
        activeMatch: locale === 'en' ? '/community' : `${prefix}/community`,
      },
    ],
    sidebar: {
      [guideKey]: guideSidebar(locale, t as unknown as Record<string, string>),
      [archKey]: architectureSidebar(locale, t as unknown as Record<string, string>),
      [apiKey]: apiSidebar(locale, t as unknown as Record<string, string>),
      ...(locale !== 'en'
        ? {
            [`/${locale}/`]: guideSidebar(locale, t as unknown as Record<string, string>),
          }
        : {}),
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/PStarH/Commander' }],
    search: {
      provider: 'local',
      options: {
        locales: {
          zh: {
            translations: {
              button: { buttonText: '搜索', buttonAriaLabel: '搜索' },
              modal: {
                noResultsText: '没有结果',
                resetButtonTitle: '清除',
                footer: { selectText: '选择', navigateText: '切换', closeText: '关闭' },
              },
            },
          },
          ja: {
            translations: {
              button: { buttonText: '検索', buttonAriaLabel: '検索' },
              modal: {
                noResultsText: '結果なし',
                resetButtonTitle: 'クリア',
                footer: { selectText: '選択', navigateText: '移動', closeText: '閉じる' },
              },
            },
          },
          ko: {
            translations: {
              button: { buttonText: '검색', buttonAriaLabel: '검색' },
              modal: {
                noResultsText: '결과 없음',
                resetButtonTitle: '지우기',
                footer: { selectText: '선택', navigateText: '이동', closeText: '닫기' },
              },
            },
          },
          es: {
            translations: {
              button: { buttonText: 'Buscar', buttonAriaLabel: 'Buscar' },
              modal: {
                noResultsText: 'Sin resultados',
                resetButtonTitle: 'Limpiar',
                footer: { selectText: 'Seleccionar', navigateText: 'Navegar', closeText: 'Cerrar' },
              },
            },
          },
          fr: {
            translations: {
              button: { buttonText: 'Rechercher', buttonAriaLabel: 'Rechercher' },
              modal: {
                noResultsText: 'Aucun résultat',
                resetButtonTitle: 'Effacer',
                footer: { selectText: 'Sélectionner', navigateText: 'Naviguer', closeText: 'Fermer' },
              },
            },
          },
        },
      },
    },
    editLink: {
      pattern: 'https://github.com/PStarH/commander-docs/edit/master/:path',
      text: t.edit,
    },
    lastUpdated: {
      text: t.updated,
      formatOptions: { dateStyle: 'medium' },
    },
    outline: { level: [2, 3], label: t.onThisPage },
    docFooter: { prev: t.prev, next: t.next },
    footer: {
      message: t.footerMsg,
      copyright: 'Copyright © 2026 Commander Contributors',
    },
  }
}

export default defineConfig({
  title: 'Commander',
  description,
  base: '/commander-docs/',
  cleanUrls: false,
  lastUpdated: true,
  ignoreDeadLinks: [/^https?:\/\/localhost/],
  sitemap: { hostname: 'https://pstarh.github.io/commander-docs/' },
  vite: {
    ssr: { noExternal: ['gsap', 'gsap/ScrollTrigger'] },
  },
  head,
  locales: {
    root: {
      label: 'English',
      lang: 'en-US',
      description: descriptions.en,
      themeConfig: themeFor('en'),
    },
    zh: {
      label: '简体中文',
      lang: 'zh-CN',
      link: '/zh/',
      description: descriptions.zh,
      themeConfig: themeFor('zh'),
    },
    ja: {
      label: '日本語',
      lang: 'ja-JP',
      link: '/ja/',
      description: descriptions.ja,
      themeConfig: themeFor('ja'),
    },
    ko: {
      label: '한국어',
      lang: 'ko-KR',
      link: '/ko/',
      description: descriptions.ko,
      themeConfig: themeFor('ko'),
    },
    es: {
      label: 'Español',
      lang: 'es-ES',
      link: '/es/',
      description: descriptions.es,
      themeConfig: themeFor('es'),
    },
    fr: {
      label: 'Français',
      lang: 'fr-FR',
      link: '/fr/',
      description: descriptions.fr,
      themeConfig: themeFor('fr'),
    },
  },
})
